name: dart_epub_http
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  archive: '>=3.3.0'
  xml: '>=6.1.0'
  path: '>=1.8.2'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
